name: Test Workflow

run-name: 'Test Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
    workflow_dispatch:


jobs:
  test:
    name: Testing
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Version
        id: getVersion
        run: echo "CURRENT_VERSION=$(mvn help:evaluate -D'expression=project.version' -q -D'forceStdout')" >> $GITHUB_OUTPUT

      - name: Get Stuff
        run: |
           IFS='-'
           read -ra arr <<< "$VERSION"
           for val in "${arr[@]}"
             do
               print "$val\n"
             done
        env:
          VERSION: ${{steps.getVersion.outputs.CURRENT_VERSION}}
