name: Test Workflow

run-name: 'Test Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
    workflow_dispatch:


jobs:
  test:
    name: Testing
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Version
        id: getVersion
        run: echo "CURRENT_VERSION=$(mvn help:evaluate -D'expression=project.version' -q -D'forceStdout')" >> $env:$GITHUB_OUTPUT

      - name: New Release Property
        id: new_release_property
        run: |
           IFS='-'
           read -ra arr <<< "$VERSION"
           for val in "${arr[@]}"
             do
               if [[ $val == r* ]]; then
                   echo "NEW_RELEASE_PROPERTY=$val" >> $GITHUB_OUTPUT
               fi
             done
        env:
          VERSION: ${{steps.getVersion.outputs.CURRENT_VERSION}}

      - name: Update Release Candidate Property
        run: |
          mvn versions:set-property \
            -D'property=core.artifact.release' \
            -D'newVersion=$RELEASE_PROPERTY
             git config user.name "ikmdevops"
             git config user.email ${{ inputs.ikmdevops_email }}
             git pull -p
             git commit -am"Updated Release Candidate to $RELEASE_PROPERTY"
             git push
        env:
         RELEASE_PROPERTY: ${{steps.new_release_property.outputs.NEW_RELEASE_PROPERTY}}
         
